export interface SeoPage {
  slug: string;
  title: string;
  description: string;
  h1: string;
  intro: string;
  keywords: string[];
  priority: number;
  changefreq: "daily" | "weekly" | "monthly";
}

export const mainSeoRoutes = [
  {
    path: "/",
    title: "Chuyển Phát 24H - Chuyển phát hỏa tốc liên tỉnh từ Hà Nội",
    description: "Chuyển phát hỏa tốc liên tỉnh, nhận hàng tận nơi tại Hà Nội và giao tận tay trong ngày theo tuyến xe đang chạy.",
    priority: 1,
    changefreq: "daily" as const,
  },
  {
    path: "/tao-don",
    title: "Tạo đơn chuyển phát hỏa tốc liên tỉnh - Chuyển Phát 24H",
    description: "Tạo đơn gửi hàng liên tỉnh nhanh, nhận tư vấn giá và điều phối xe phù hợp từ Hà Nội đi các tỉnh.",
    priority: 0.9,
    changefreq: "daily" as const,
  },
  {
    path: "/tra-cuu",
    title: "Tra cứu đơn hàng Chuyển Phát 24H",
    description: "Tra cứu trạng thái đơn chuyển phát bằng mã đơn và số điện thoại, cập nhật thông tin tài xế và tiến trình giao hàng.",
    priority: 0.75,
    changefreq: "daily" as const,
  },
  {
    path: "/tuyen-chuyen-phat",
    title: "Tuyến chuyển phát liên tỉnh từ Hà Nội - Chuyển Phát 24H",
    description: "Danh sách tuyến chuyển phát 2 chiều từ Hà Nội đi Bắc Ninh, Hải Phòng, Ninh Bình, Nghệ An và các tỉnh phía Bắc.",
    priority: 0.85,
    changefreq: "weekly" as const,
  },
  {
    path: "/bang-gia",
    title: "Bảng giá chuyển phát hỏa tốc liên tỉnh - Chuyển Phát 24H",
    description: "Tham khảo giá gửi giấy tờ, hàng shop, thực phẩm, hàng cồng kềnh và dịch vụ chuyển phát liên tỉnh trong ngày.",
    priority: 0.8,
    changefreq: "weekly" as const,
  },
  {
    path: "/chinh-sach",
    title: "Chính sách dịch vụ chuyển phát - Chuyển Phát 24H",
    description: "Quy định gửi hàng, xác nhận giá, bảo quản hàng hóa, trách nhiệm vận chuyển và hỗ trợ khách hàng.",
    priority: 0.55,
    changefreq: "monthly" as const,
  },
  {
    path: "/lien-he",
    title: "Liên hệ Chuyển Phát 24H",
    description: "Liên hệ hotline Chuyển Phát 24H để gửi hàng hỏa tốc liên tỉnh, báo giá và điều phối xe nhận hàng tận nơi.",
    priority: 0.7,
    changefreq: "weekly" as const,
  },
];

export const seoPages: SeoPage[] = [
  {
    slug: "chuyen-phat-hoa-toc-lien-tinh",
    title: "Chuyển phát hỏa tốc liên tỉnh - Nhận tận nơi, giao tận tay",
    description: "Dịch vụ chuyển phát hỏa tốc liên tỉnh từ Hà Nội, nhận hàng tận nơi và giao tận tay theo tuyến xe đang chạy.",
    h1: "Chuyển phát hỏa tốc liên tỉnh",
    intro: "Chuyển Phát 24H nhận giấy tờ, hàng shop, thực phẩm và hàng cần giao gấp từ Hà Nội đi các tỉnh phía Bắc theo tuyến xe đang chạy.",
    keywords: ["chuyển phát hỏa tốc liên tỉnh", "gửi hàng liên tỉnh", "giao hàng trong ngày"],
    priority: 0.9,
    changefreq: "weekly",
  },
  {
    slug: "gui-giay-to-hoa-toc-di-tinh",
    title: "Gửi giấy tờ hỏa tốc đi tỉnh - Chuyển Phát 24H",
    description: "Gửi hồ sơ, chứng từ, hợp đồng hỏa tốc từ Hà Nội đi tỉnh, nhận tận nơi và giao tận tay trong ngày.",
    h1: "Gửi giấy tờ hỏa tốc đi tỉnh",
    intro: "Phù hợp với hồ sơ, chứng từ, hợp đồng và tài liệu cần giao nhanh, có mã đơn để khách hàng theo dõi trạng thái.",
    keywords: ["gửi giấy tờ hỏa tốc", "gửi hồ sơ đi tỉnh", "chuyển phát chứng từ"],
    priority: 0.82,
    changefreq: "weekly",
  },
  {
    slug: "gui-hang-cong-kenh-di-tinh",
    title: "Gửi hàng cồng kềnh đi tỉnh - Điều phối xe phù hợp",
    description: "Nhận gửi hàng cồng kềnh, hàng nặng đi tỉnh, báo giá thủ công và điều phối xe phù hợp với từng đơn.",
    h1: "Gửi hàng cồng kềnh đi tỉnh",
    intro: "Các đơn hàng cồng kềnh được nhân viên xác nhận kích thước, trọng lượng và tuyến giao trước khi điều phối xe.",
    keywords: ["gửi hàng cồng kềnh", "vận chuyển hàng nặng", "chuyển hàng đi tỉnh"],
    priority: 0.78,
    changefreq: "weekly",
  },
  {
    slug: "van-chuyen-xe-may-di-tinh",
    title: "Vận chuyển xe máy đi tỉnh - Chuyển Phát 24H",
    description: "Dịch vụ vận chuyển xe máy đi tỉnh, xác nhận lịch xe, phương án bốc xếp và báo giá trước khi nhận đơn.",
    h1: "Vận chuyển xe máy đi tỉnh",
    intro: "Chuyển Phát 24H hỗ trợ vận chuyển xe máy theo tuyến phù hợp, ưu tiên bảo quản và xác nhận rõ lịch giao nhận.",
    keywords: ["vận chuyển xe máy đi tỉnh", "gửi xe máy liên tỉnh", "chuyển xe máy"],
    priority: 0.72,
    changefreq: "monthly",
  },
  {
    slug: "chuyen-phat-trong-ngay-tu-ha-noi",
    title: "Chuyển phát trong ngày từ Hà Nội đi tỉnh",
    description: "Gửi hàng trong ngày từ Hà Nội đi các tỉnh theo tuyến xe chạy liên tục, nhận hàng tận nơi và giao tận tay.",
    h1: "Chuyển phát trong ngày từ Hà Nội",
    intro: "Dịch vụ phù hợp với hàng cần giao nhanh, hàng shop, giấy tờ và thực phẩm cần đi ngay theo tuyến xe đang chạy.",
    keywords: ["chuyển phát trong ngày từ Hà Nội", "giao hàng trong ngày", "gửi hàng đi tỉnh"],
    priority: 0.86,
    changefreq: "weekly",
  },
  {
    slug: "chuyen-phat-ha-noi-bac-ninh",
    title: "Chuyển phát Hà Nội Bắc Ninh trong ngày",
    description: "Nhận gửi hàng Hà Nội đi Bắc Ninh và chiều ngược lại, tuyến gần 2-4 giờ tùy khu vực và lịch xe.",
    h1: "Chuyển phát Hà Nội Bắc Ninh",
    intro: "Tuyến Hà Nội - Bắc Ninh phù hợp với giấy tờ, hàng shop, linh kiện nhỏ và các đơn cần giao nhanh trong ngày.",
    keywords: ["chuyển phát Hà Nội Bắc Ninh", "gửi hàng Bắc Ninh", "giao hàng Bắc Ninh"],
    priority: 0.84,
    changefreq: "weekly",
  },
  {
    slug: "chuyen-phat-ha-noi-hai-phong",
    title: "Chuyển phát Hà Nội Hải Phòng trong ngày",
    description: "Dịch vụ gửi hàng Hà Nội đi Hải Phòng theo tuyến cao tốc, nhận tận nơi và giao tận tay trong ngày.",
    h1: "Chuyển phát Hà Nội Hải Phòng",
    intro: "Tuyến Hà Nội - Hải Phòng hỗ trợ giao nhận hai chiều, phù hợp với hàng cần chuyển nhanh, rõ trạng thái đơn.",
    keywords: ["chuyển phát Hà Nội Hải Phòng", "gửi hàng Hải Phòng", "giao hàng Hải Phòng"],
    priority: 0.84,
    changefreq: "weekly",
  },
  {
    slug: "chuyen-phat-ha-noi-quang-ninh",
    title: "Chuyển phát Hà Nội Quảng Ninh - Hạ Long, Cẩm Phả, Móng Cái",
    description: "Nhận gửi hàng từ Hà Nội đi Quảng Ninh, Hạ Long, Cẩm Phả, Móng Cái theo lịch xe phù hợp.",
    h1: "Chuyển phát Hà Nội Quảng Ninh",
    intro: "Các tuyến Quảng Ninh được xác nhận lịch xe và thời gian giao dự kiến trước khi điều phối.",
    keywords: ["chuyển phát Hà Nội Quảng Ninh", "gửi hàng Hạ Long", "gửi hàng Móng Cái"],
    priority: 0.8,
    changefreq: "weekly",
  },
  {
    slug: "chuyen-phat-ha-noi-ninh-binh",
    title: "Chuyển phát Hà Nội Ninh Bình trong ngày",
    description: "Gửi hàng Hà Nội đi Ninh Bình, nhận hàng tận nơi, giao tận tay và cập nhật trạng thái đơn.",
    h1: "Chuyển phát Hà Nội Ninh Bình",
    intro: "Chuyển Phát 24H hỗ trợ tuyến Hà Nội - Ninh Bình cho giấy tờ, hàng shop, thực phẩm và hàng cần giao nhanh.",
    keywords: ["chuyển phát Hà Nội Ninh Bình", "gửi hàng Ninh Bình", "giao hàng Ninh Bình"],
    priority: 0.78,
    changefreq: "weekly",
  },
  {
    slug: "chuyen-phat-ha-noi-thanh-hoa",
    title: "Chuyển phát Hà Nội Thanh Hóa trong ngày hoặc 24h",
    description: "Dịch vụ gửi hàng Hà Nội đi Thanh Hóa theo tuyến QL1A, xác nhận thời gian và giá trước khi vận chuyển.",
    h1: "Chuyển phát Hà Nội Thanh Hóa",
    intro: "Tuyến Thanh Hóa phù hợp với hàng cần đi trong ngày hoặc trong 24h, tùy điểm nhận, điểm giao và lịch xe.",
    keywords: ["chuyển phát Hà Nội Thanh Hóa", "gửi hàng Thanh Hóa", "vận chuyển Thanh Hóa"],
    priority: 0.78,
    changefreq: "weekly",
  },
  {
    slug: "chuyen-phat-ha-noi-nghe-an",
    title: "Chuyển phát Hà Nội Nghệ An trong 24h",
    description: "Nhận gửi hàng Hà Nội đi Nghệ An, báo giá và xác nhận lịch xe trước khi điều phối.",
    h1: "Chuyển phát Hà Nội Nghệ An",
    intro: "Tuyến Nghệ An là tuyến xa, cần xác nhận lịch xe và thời gian giao dự kiến để đảm bảo phù hợp với nhu cầu khách hàng.",
    keywords: ["chuyển phát Hà Nội Nghệ An", "gửi hàng Nghệ An", "vận chuyển Nghệ An"],
    priority: 0.76,
    changefreq: "weekly",
  },
];
