import { Customer, Driver, Vehicle, Route, Order, OrderStatus, PricingRule, ContentPage } from "./types";

export const PROVINCES_MAP: Record<string, string[]> = {
  "Hà Nội": [
    "Cầu Giấy", "Ba Đình", "Hoàn Kiếm", "Hai Bà Trưng", "Đống Đa", "Tây Hồ", 
    "Thanh Xuân", "Hoàng Mai", "Long Biên", "Hà Đông", "Nam Từ Liêm", "Bắc Từ Liêm", 
    "Thanh Trì", "Gia Lâm", "Đông Anh", "Sóc Sơn", "Hoài Đức"
  ],
  "Bắc Ninh": ["TP Bắc Ninh", "Từ Sơn", "Quế Võ", "Yên Phong", "Tiên Du", "Thuận Thành", "Gia Bình", "Lương Tài"],
  "Hưng Yên": ["TP Hưng Yên", "Văn Giang", "Mỹ Hào", "Yên Mỹ", "Khoái Châu", "Ân Thi", "Kim Động", "Phù Cừ", "Tiên Lữ", "Văn Lâm"],
  "Vĩnh Phúc": ["Vĩnh Yên", "Phúc Yên", "Bình Xuyên", "Tam Đảo", "Yên Lạc", "Vĩnh Tường", "Lập Thạch", "Sông Lô", "Tam Dương"],
  "Hà Nam": ["Phủ Lý", "Duy Tiên", "Kim Bảng", "Lý Nhân", "Thanh Liêm", "Bình Lục"],
  "Hải Dương": ["TP Hải Dương", "Chí Linh", "Kinh Môn", "Cẩm Giàng", "Bình Giang", "Gia Lộc", "Kim Thành", "Nam Sách", "Thanh Hà", "Thanh Miện", "Tứ Kỳ"],
  "Thái Nguyên": ["TP Thái Nguyên", "Sông Công", "Phổ Yên", "Đại Từ", "Phú Bình", "Đồng Hỷ", "Võ Nhai", "Định Hóa", "Phú Lương"],
  "Bắc Giang": ["TP Bắc Giang", "Việt Yên", "Yên Dũng", "Lạng Giang", "Hiệp Hòa", "Tân Yên", "Lục Nam", "Lục Ngạn", "Sơn Động", "Yên Thế"],
  "Hòa Bình": ["TP Hòa Bình", "Lương Sơn", "Mai Châu", "Kim Bôi", "Cao Phong", "Đà Bắc", "Lạc Sơn", "Lạc Thủy", "Yên Thủy"],
  "Hải Phòng": ["Quận Hồng Bàng", "Quận Ngô Quyền", "Quận Lê Chân", "Quận Hải An", "Quận Thanh Khê", "Thủy Nguyên", "An Dương", "Đồ Sơn", "Cát Bà", "Kiến An", "An Lão", "Vĩnh Bảo", "Tiên Lãng"],
  "Quảng Ninh": ["Hạ Long", "Uông Bí", "Cẩm Phả", "Móng Cái", "Vân Đồn", "Đông Triều", "Quảng Yên", "Hoành Bồ", "Đầm Hà", "Tiên Yên", "Bình Liêu", "Cô Tô"],
  "Ninh Bình": ["TP Ninh Bình", "Tam Điệp", "Hoa Lư", "Gia Viễn", "Nho Quan", "Yên Khánh", "Yên Mô", "Kim Sơn"],
  "Nam Định": ["TP Nam Định", "Mỹ Lộc", "Vụ Bản", "Ý Yên", "Hải Hậu", "Nam Trực", "Trực Ninh", "Xuân Trường", "Giao Thủy", "Nghĩa Hưng"],
  "Thái Bình": ["TP Thái Bình", "Đông Hưng", "Hưng Hà", "Quỳnh Phụ", "Tiền Hải", "Vũ Thư", "Kiến Xương", "Thái Thụy"],
  "Phú Thọ": ["Việt Trì", "TX Phú Thọ", "Lâm Thao", "Thanh Sơn", "Đoan Hùng", "Hạ Hòa", "Phù Ninh", "Tam Nông", "Thanh Ba", "Thanh Thủy", "Yên Lập"],
  "Tuyên Quang": ["TP Tuyên Quang", "Sơn Dương", "Yên Sơn", "Chiêm Hóa", "Hàm Yên", "Na Hang", "Lâm Bình"],
  "Lạng Sơn": ["TP Lạng Sơn", "Hữu Lũng", "Chi Lăng", "Cao Lộc", "Tràng Định", "Bình Gia", "Văn Lãng", "Văn Quan", "Bắc Sơn", "Hữu Khánh"],
  "Yên Bái": ["TP Yên Bái", "Nghĩa Lộ", "Văn Chấn", "Trấn Yên", "Lục Yên", "Mù Cang Chải", "Trạm Tấu", "Văn Yên", "Yên Bình"],
  "Lào Cai": ["TP Lào Cai", "Sa Pa", "Bảo Thắng", "Bảo Yên", "Bát Xát", "Mường Khương", "Si Ma Cai", "Bắc Hà", "Văn Bàn"],
  "Sơn La": ["TP Sơn La", "Mộc Châu", "Mai Sơn", "Mường La", "Phù Yên", "Quỳnh Nhai", "Sông Mã", "Thuận Châu", "Vân Hồ", "Yên Châu"],
  "Lai Châu": ["TP Lai Châu", "Phong Thổ", "Sìn Hồ", "Mường Tè", "Than Uyên", "Tân Uyên", "Nậm Nhùn", "Tam Đường"],
  "Thanh Hóa": ["TP Thanh Hóa", "Sầm Sơn", "Bỉm Sơn", "Nghi Sơn", "Đông Sơn", "Quảng Xương", "Hoằng Hóa", "Hậu Lộc", "Yên Định", "Thọ Xuân", "Triệu Sơn"],
  "Nghệ An": ["TP Vinh", "Cửa Lò", "Diễn Châu", "Quỳnh Lưu", "Hoàng Mai", "Nghi Lộc", "Thái Hòa", "Nghĩa Đàn", "Quỳ Hợp", "Con Cuông", "Anh Sơn"]
};

export const MOCK_CUSTOMERS: Customer[] = [
  { id: "C-01", name: "Lê Minh Tuấn", phone: "0912345678", email: "tuan.le@gmail.com", type: "Shop online", defaultAddress: "12 Chùa Bộc, Đống Đa, Hà Nội", totalOrders: 42, createdAt: "2026-01-10T08:00:00Z" },
  { id: "C-02", name: "Nguyễn Thị Hương", phone: "0987654321", email: "huong.nguyen@gmail.com", type: "Cá nhân", defaultAddress: "45 Trần Duy Hưng, Cầu Giấy, Hà Nội", totalOrders: 5, createdAt: "2026-03-15T09:30:00Z" },
  { id: "C-03", name: "Công ty Hoàng Minh", phone: "02439998888", email: "contact@hoangminh.vn", type: "Doanh nghiệp", defaultAddress: "Tòa Keangnam, Mễ Trì, Nam Từ Liêm, Hà Nội", totalOrders: 156, createdAt: "2025-08-20T10:00:00Z" },
  { id: "C-04", name: "Showroom Yamaha Town", phone: "0966777888", type: "Showroom", defaultAddress: "250 Nguyễn Trãi, Thanh Xuân, Hà Nội", totalOrders: 19, createdAt: "2026-02-01T14:20:00Z" },
  { id: "C-05", name: "Gara Ô tô Mỹ Đình", phone: "0934567890", type: "Gara", defaultAddress: "Ngõ 20 Phạm Hùng, Nam Từ Liêm, Hà Nội", totalOrders: 8, createdAt: "2026-04-18T11:15:00Z" }
];

export const MOCK_DRIVERS: Driver[] = [
  { id: "D-01", name: "Nguyễn Văn A", phone: "0901234567", avatar: "https://images.unsplash.com/photo-1540569014015-19a7be504e3a?auto=format&fit=crop&q=80&w=120&h=120", vehicleId: "V-01", status: "Rảnh", rating: 4.9, notes: "Chuyên tuyến Hà Nội ↔ Ninh Bình, chạy đúng giờ, cẩn thận" },
  { id: "D-02", name: "Trần Văn B", phone: "0902345678", avatar: "https://images.unsplash.com/photo-1566492031773-4f4e44671857?auto=format&fit=crop&q=80&w=120&h=120", vehicleId: "V-02", status: "Đang chạy tuyến", rating: 4.8, notes: "Xe 16 chỗ chuyên ghép hàng hỏa tốc Hà Nội ↔ Hải Phòng" },
  { id: "D-03", name: "Lê Văn C", phone: "0903456789", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=120&h=120", vehicleId: "V-03", status: "Đang nhận hàng", rating: 4.7, notes: "Bán tải, nhận bốc xếp hàng cồng kềnh Hà Nội ↔ Quảng Ninh" },
  { id: "D-04", name: "Phạm Văn D", phone: "0904567890", avatar: "https://images.unsplash.com/photo-1628157582853-a796fa650a6a?auto=format&fit=crop&q=80&w=120&h=120", vehicleId: "V-04", status: "Rảnh", rating: 4.9, notes: "Xe tải nhỏ chuyên hàng ghép quá khổ, chuyển xe máy an toàn" },
  { id: "D-05", name: "Đỗ Văn E", phone: "0905678901", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=120&h=120", vehicleId: "V-05", status: "Rảnh", rating: 4.6, notes: "Xe 7 chỗ chạy liên tục tuyến Hà Nội ↔ Bắc Ninh/Hưng Yên" }
];

export const MOCK_VEHICLES: Vehicle[] = [
  { id: "V-01", type: "Xe 7 chỗ", plateNumber: "29A-123.45", capacity: "450 kg", cargoDimensions: "150x120x100 cm", status: "Hoạt động", notes: "Khoang hành lý rộng rãi" },
  { id: "V-02", type: "Xe 16 chỗ", plateNumber: "29B-678.90", capacity: "1.2 tấn", cargoDimensions: "280x160x150 cm", status: "Hoạt động", notes: "Đã tháo 2 hàng ghế sau để xếp thùng hàng" },
  { id: "V-03", type: "Bán tải", plateNumber: "29C-555.23", capacity: "800 kg", cargoDimensions: "150x140x110 cm", status: "Hoạt động", notes: "Thùng cao có nắp đậy, chống nước tuyệt đối" },
  { id: "V-04", type: "Xe tải nhỏ", plateNumber: "29D-444.88", capacity: "1.5 tấn", cargoDimensions: "320x170x180 cm", status: "Hoạt động", notes: "Thùng kín inox bửng nâng hạ tự động" },
  { id: "V-05", type: "Xe 7 chỗ", plateNumber: "30E-234.56", capacity: "450 kg", cargoDimensions: "150x120x100 cm", status: "Hoạt động", notes: "Phục vụ hỏa tốc bưu phẩm nhỏ" },
  { id: "V-06", type: "Xe máy", plateNumber: "29F-999.99", capacity: "80 kg", cargoDimensions: "Thùng sau 50x50x50 cm", status: "Hoạt động" }
];

// Active mock schedule representing "Tuyến xe đang chạy hôm nay"
export const MOCK_ROUTES: Route[] = [
  {
    id: "R-01",
    name: "Hà Nội ↔ Bắc Ninh (Chuyến Chiều)",
    originProvince: "Hà Nội",
    destinationProvince: "Bắc Ninh",
    direction: "Hà Nội đi Tỉnh",
    departureTime: "14:30",
    estimatedDuration: "1h30",
    serviceLevel: "Thời gian: 2–4 giờ",
    driverId: "D-05",
    vehicleId: "V-05",
    capacityStatus: "Trống nhiều",
    routeStatus: "Đang nhận hàng",
    remainingOrderSlots: 3,
    acceptedItemTypes: ["Giấy tờ / Hồ sơ", "Bưu phẩm nhỏ", "Hàng shop"],
    notes: "Có xe riêng di chuyển qua Từ Sơn, TP Bắc Ninh"
  },
  {
    id: "R-02",
    name: "Hà Nội ↔ Hải Phòng (Chuyến Tốc Hành)",
    originProvince: "Hà Nội",
    destinationProvince: "Hải Phòng",
    direction: "Hà Nội đi Tỉnh",
    departureTime: "15:00",
    estimatedDuration: "2h30",
    serviceLevel: "Thời gian: Trong ngày (3-6h)",
    driverId: "D-02",
    vehicleId: "V-02",
    capacityStatus: "Còn trống vừa",
    routeStatus: "Đang nhận hàng",
    remainingOrderSlots: 2,
    acceptedItemTypes: ["Bưu phẩm nhỏ", "Hàng shop", "Hàng cồng kềnh vừa"],
    notes: "Khởi hành từ bến xe Giáp Bát dọc cao tốc 5B"
  },
  {
    id: "R-03",
    name: "Hà Nội ↔ Ninh Bình (Tuyến Hàng Cao Cấp)",
    originProvince: "Hà Nội",
    destinationProvince: "Ninh Bình",
    direction: "Hà Nội đi Tỉnh",
    departureTime: "16:00",
    estimatedDuration: "2h00",
    serviceLevel: "Thời gian: Trong ngày",
    driverId: "D-01",
    vehicleId: "V-01",
    capacityStatus: "Sắp đầy",
    routeStatus: "Đang nhận hàng",
    remainingOrderSlots: 2,
    acceptedItemTypes: ["Giấy tờ / Hồ sơ", "Xe máy", "Hàng điện tử"],
    notes: "Xe riêng cao cấp thích hợp vận chuyển hàng dễ vỡ"
  },
  {
    id: "R-04",
    name: "Hà Nội ↔ Thanh Hóa (Chuyến Tối)",
    originProvince: "Hà Nội",
    destinationProvince: "Thanh Hóa",
    direction: "Hà Nội đi Tỉnh",
    departureTime: "18:00",
    estimatedDuration: "3h30",
    serviceLevel: "Thời gian: Trong ngày / 24h",
    driverId: "D-04",
    vehicleId: "V-04",
    capacityStatus: "Còn trống vừa",
    routeStatus: "Đang nhận hàng",
    remainingOrderSlots: 5,
    acceptedItemTypes: ["Hàng shop", "Hàng cồng kềnh", "Xe máy"],
    notes: "Chạy dọc quốc lộ 1A nhận trả dọc đường lớn"
  },
  {
    id: "R-05",
    name: "Nghệ An ↔ Hà Nội (Chiều Về)",
    originProvince: "Nghệ An",
    destinationProvince: "Hà Nội",
    direction: "Tỉnh về Hà Nội",
    departureTime: "20:00",
    estimatedDuration: "5h30",
    serviceLevel: "Thời gian: Giao trong đêm / Sáng mai",
    driverId: "D-04",
    vehicleId: "V-04",
    capacityStatus: "Trống nhiều",
    routeStatus: "Sắp chạy",
    remainingOrderSlots: 8,
    acceptedItemTypes: ["Hàng nhỏ", "Hàng cồng kềnh", "Giấy tờ"],
    notes: "Chuyến hồi từ Vinh về Hà Nội lấy tận nơi trung tâm tp"
  },
  {
    id: "R-06",
    name: "Lào Cai ↔ Hà Nội (Chiều Về)",
    originProvince: "Lào Cai",
    destinationProvince: "Hà Nội",
    direction: "Tỉnh về Hà Nội",
    departureTime: "22:00",
    estimatedDuration: "5h00",
    serviceLevel: "Cần xác nhận lịch xe",
    driverId: "D-03",
    vehicleId: "V-03",
    capacityStatus: "Còn trống vừa",
    routeStatus: "Sắp chạy",
    remainingOrderSlots: 4,
    acceptedItemTypes: ["Giấy tờ / Hồ sơ", "Hàng nhỏ"],
    notes: "Cần xác nhận trước lịch trình do đi đèo Tây Bắc"
  }
];

export const MOCK_ORDERS: Order[] = [
  {
    id: "ORD-001",
    orderCode: "CP24H-20260616-0130",
    customerId: "C-01",
    senderName: "Lê Minh Tuấn",
    senderPhone: "0912345678",
    pickupAddress: "12 Chùa Bộc",
    pickupDistrict: "Đống Đa",
    pickupProvince: "Hà Nội",
    receiverName: "Phạm Hùng Sơn",
    receiverPhone: "0905111222",
    deliveryAddress: "124 Lạch Tray",
    deliveryDistrict: "Quận Ngô Quyền",
    deliveryProvince: "Hải Phòng",
    direction: "Hà Nội đi Tỉnh",
    routeName: "Hà Nội ↔ Hải Phòng",
    itemType: "Giấy tờ/chứng từ",
    itemDescription: "Bì thư hồ sơ thầu dự án cầu Hải Phòng (bắt buộc đóng túi niêm phong)",
    weight: 1,
    declaredValue: 5000000,
    serviceType: "Hỏa tốc 2-4h",
    expectedPickupTime: "14:00 16/06/2026",
    expectedDeliveryTime: "17:30 16/06/2026",
    quotedPrice: 350000,
    finalPrice: 350000,
    status: OrderStatus.IN_TRANSIT,
    assignedDriverId: "D-02",
    assignedVehicleId: "V-02",
    assignedRouteId: "R-02",
    paymentStatus: "Đã thanh toán",
    internalNotes: "Hàng thầu gấp, tài xế gọi báo khi hoàn thành để kế toán xác nhận",
    createdAt: "2026-06-16T12:00:00Z",
    updatedAt: "2026-06-16T14:45:00Z"
  },
  {
    id: "ORD-002",
    orderCode: "CP24H-20260616-2005",
    customerId: "C-04",
    senderName: "Yamaha Town Nguyễn Trãi",
    senderPhone: "0966777888",
    pickupAddress: "250 Nguyễn Trãi",
    pickupDistrict: "Thanh Xuân",
    pickupProvince: "Hà Nội",
    receiverName: "Hoàng Văn Tiến",
    receiverPhone: "0914222333",
    deliveryAddress: "Đền Trần, TP Nam Định",
    deliveryDistrict: "TP Nam Định",
    deliveryProvince: "Nam Định",
    direction: "Hà Nội đi Tỉnh",
    routeName: "Hà Nội ↔ Nam Định",
    itemType: "Xe máy",
    itemDescription: "Xe máy Yamaha Exciter mới 100% bọc mút xốp không xăng",
    weight: 115,
    declaredValue: 48000000,
    serviceType: "Xe riêng",
    expectedPickupTime: "15:30 16/06/2026",
    expectedDeliveryTime: "18:30 16/06/2026",
    quotedPrice: 1200000,
    finalPrice: 1200000,
    status: OrderStatus.ASSIGNED,
    assignedDriverId: "D-04",
    assignedVehicleId: "V-04",
    paymentStatus: "Đã cọc",
    internalNotes: "Chuyển showroom showroom tỉnh nhận, kiểm tra xe không xước sát kĩ trước khi ký biên nhận",
    createdAt: "2026-06-16T11:20:00Z",
    updatedAt: "2026-06-16T15:10:00Z"
  },
  {
    id: "ORD-003",
    orderCode: "CP24H-20260616-0419",
    customerId: "C-02",
    senderName: "Nguyễn Thị Hương",
    senderPhone: "0987654321",
    pickupAddress: "45 Trần Duy Hưng",
    pickupDistrict: "Cầu Giấy",
    pickupProvince: "Hà Nội",
    receiverName: "Đỗ Thị Hà",
    receiverPhone: "0967333444",
    deliveryAddress: "Phường Ba Đình, TP Thanh Hóa",
    deliveryDistrict: "TP Thanh Hóa",
    deliveryProvince: "Thanh Hóa",
    direction: "Hà Nội đi Tỉnh",
    routeName: "Hà Nội ↔ Thanh Hóa",
    itemType: "Hàng shop",
    itemDescription: "Váy đầm cao cấp đóng hộp giấy quà tặng",
    weight: 2,
    declaredValue: 2500000,
    serviceType: "Trong ngày",
    expectedPickupTime: "16:00 16/06/2026",
    expectedDeliveryTime: "20:30 16/06/2026",
    quotedPrice: 220000,
    finalPrice: 220000,
    status: OrderStatus.PENDING_CONFIRMATION,
    paymentStatus: "Chưa thanh toán",
    internalNotes: "KH cần giao gấp ăn cưới, đề xuất chuyển chuyến Thanh Hóa lúc 18h",
    createdAt: "2026-06-16T15:05:00Z",
    updatedAt: "2026-06-16T15:05:00Z"
  }
];

export const MOCK_PRICING_RULES: PricingRule[] = [
  {
    id: "PR-01",
    originProvince: "Hà Nội",
    destinationProvince: "Bắc Ninh",
    direction: "Hà Nội đi Tỉnh",
    itemType: "Giấy tờ/chứng từ",
    serviceType: "Hỏa tốc 2-4h",
    basePrice: 150000,
    pricePerKg: 10000,
    bulkyFee: 0,
    fragileFee: 0,
    nightFee: 30000,
    loadingFee: 0,
    insuranceRate: 0.005,
    minPrice: 150000,
    isManualQuoteRequired: false,
    isActive: true
  },
  {
    id: "PR-02",
    originProvince: "Hà Nội",
    destinationProvince: "Hải Phòng",
    direction: "Hà Nội đi Tỉnh",
    itemType: "Hàng nhỏ / Shop",
    serviceType: "Trong ngày",
    basePrice: 180000,
    pricePerKg: 15000,
    bulkyFee: 50000,
    fragileFee: 20000,
    nightFee: 40000,
    loadingFee: 20000,
    insuranceRate: 0.005,
    minPrice: 180000,
    isManualQuoteRequired: false,
    isActive: true
  },
  {
    id: "PR-03",
    originProvince: "Hà Nội",
    destinationProvince: "Nghệ An",
    direction: "Hà Nội đi Tỉnh",
    itemType: "Xe máy",
    serviceType: "Gửi 24h",
    basePrice: 850000,
    pricePerKg: 5000,
    bulkyFee: 200000,
    fragileFee: 50000,
    nightFee: 50000,
    loadingFee: 100000,
    insuranceRate: 0.01,
    minPrice: 850000,
    isManualQuoteRequired: true,
    isActive: true
  }
];

export const MOCK_CONTENT_PAGES: ContentPage[] = [
  {
    id: "P-01",
    title: "Chuyển phát hỏa tốc liên tỉnh siêu tốc",
    slug: "chuyen-phat-hoa-toc-lien-tinh",
    metaTitle: "Chuyển Phát Hỏa Tốc Liên Tỉnh giá tốt từ Hà Nội",
    metaDescription: "Dịch vụ chuyển phát liên tỉnh hỏa tốc nhận tận nơi giao tận tay trong vòng 2-4 giờ theo hệ thống xe chạy thật. Đặt đơn đi ngay không gom kho.",
    content: "Dịch vụ Vận tải Hỏa tốc Chuyển Phát 24H chuyên kết nối Hà Nội đi các tỉnh ngay trong ngày, nhận tận nơi và giao tận tay không chờ gom kho...",
    pageType: "service",
    status: "Xuất bản",
    createdAt: "2026-05-01T08:00:00Z",
    updatedAt: "2026-05-01T08:00:00Z"
  },
  {
    id: "P-02",
    title: "Quy định hàng hóa cấm vận chuyển và hạn chế bồi hoàn",
    slug: "chinh-sach-hang-cam",
    metaTitle: "Danh sách hàng cấm vận chuyển tại Chuyển Phát 24H",
    metaDescription: "Tìm hiểu quy định pháp luật cùng nội quy bồi hoàn cho các mặt hàng cấm vận chuyển như chất nổ, chất cấm,... tại chuyenphat24h.vn.",
    content: "Chuyển Phát 24H tuân thủ quy chuẩn bưu chính và pháp luật Việt Nam. Nghiêm cấm gửi ma túy, vũ khí, chất nổ, động vật quý hiếm...",
    pageType: "policy",
    status: "Xuất bản",
    createdAt: "2026-05-02T08:00:00Z",
    updatedAt: "2026-05-02T08:00:00Z"
  }
];

export const SERVICE_SEO_PAGES = [
  { slug: "chuyen-phat-hoa-toc-lien-tinh", title: "Chuyển phát hỏa tốc liên tỉnh" },
  { slug: "gui-giay-to-hoa-toc-di-tinh", title: "Gửi giấy tờ hỏa tốc đi tỉnh" },
  { slug: "gui-hang-cong-kenh-di-tinh", title: "Gửi hàng cồng kềnh đi tỉnh" },
  { slug: "van-chuyen-xe-may-di-tinh", title: "Vận chuyển xe máy đi tỉnh" },
  { slug: "gui-hang-dien-tu-di-tinh", title: "Gửi hàng điện tử đi tỉnh" },
  { slug: "chuyen-phat-trong-ngay-tu-ha-noi", title: "Chuyển phát trong ngày từ Hà Nội" },
  { slug: "chuyen-phat-24h", title: "Chuyển phát 24h liên tỉnh" },
  { slug: "chuyen-phat-ha-noi-bac-ninh", title: "Chuyển phát Hà Nội ↔ Bắc Ninh" },
  { slug: "chuyen-phat-ha-noi-hung-yen", title: "Chuyển phát Hà Nội ↔ Hưng Yên" },
  { slug: "chuyen-phat-ha-noi-hai-phong", title: "Chuyển phát Hà Nội ↔ Hải Phòng" },
  { slug: "chuyen-phat-ha-noi-quang-ninh", title: "Chuyển phát Hà Nội ↔ Quảng Ninh" },
  { slug: "chuyen-phat-ha-noi-ninh-binh", title: "Chuyển phát Hà Nội ↔ Ninh Bình" },
  { slug: "chuyen-phat-ha-noi-thanh-hoa", title: "Chuyển phát Hà Nội ↔ Thanh Hóa" },
  { slug: "chuyen-phat-ha-noi-nghe-an", title: "Chuyển phát Hà Nội ↔ Nghệ An" }
];
